<?php

namespace OpenSkool\AdminBundle\Entity\Repository;

use Yepsua\RADBundle\ORM\EntityRepository;

use OpenSkool\AdminBundle\Entity\AsignaturaEtapaPlanEstudios;

/**
 * AsignaturaEtapaPlanEstudiosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignaturaEtapaPlanEstudiosRepository extends EntityRepository
{
    const REPOSITORY_NAMESPACE = 'OpenSkoolAdminBundle:AsignaturaEtapaPlanEstudios';
    
    /**
     * Crea una nueva entidad dada los id de Etapa y PensumAsignatura
     * @param type $etapaPlanId
     * @param type $pensumAsignaturaId
     */
    public function crearPorIds($etapaPlanId, $pensumAsignaturaId){
        $em = $this->getEntityManager();
        $entity = new AsignaturaEtapaPlanEstudios();
        $entity->setEtapaPlanEstudios($em->getReference('OpenSkoolAdminBundle:EtapaPlanEstudios', $etapaPlanId));
        $entity->setPensumAsignatura($em->getReference('OpenSkoolAdminBundle:PensumAsignatura', $pensumAsignaturaId));
        $em->persist($entity);
        $em->flush();
    }
    
    /**
     * Elimina la entidad por el id.
     * @param type $asignaturaEtapaId
     */
    public function eliminarPorId($asignaturaEtapaId){
        $entity = $this->find($asignaturaEtapaId);
        $em = $this->getEntityManager();
        if($entity){
          $em->remove($entity);
          $em->flush();
        }
    }
}
