<?php

namespace OpenSkool\AdminBundle\Entity\Repository;

use Yepsua\RADBundle\ORM\EntityRepository;
use OpenSkool\AdminBundle\Entity\AsignaturaEtapaPlanEstudios;

/**
 * AsignaturaEtapaPlanEstudiosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignaturaEtapaPlanEstudiosRepository extends EntityRepository {

  const REPOSITORY_NAMESPACE = 'OpenSkoolAdminBundle:AsignaturaEtapaPlanEstudios';

  /**
   * 
   * @param integer $planEstudiosId
   * @param integer $asignaturaId
   * @return array
   */
  public function obtenerPorPlanEstudios($planEstudiosId, $asignaturaId = null) {
    $query = $this->obtenerPorPlanEstudiosQuery($planEstudiosId);
    if ($asignaturaId !== null) {
      $where = is_array($asignaturaId) ? 'asignaturaEtapaPlanEstudios NOT IN (:asignaturaId)' : 'asignaturaEtapaPlanEstudios != :asignaturaId';
      $query = $query->andWhere($where)
                     ->setParameter('asignaturaId', $asignaturaId);
    }
    return $query->getQuery()->getResult();
  }

  /**
   * 
   * @param integer $planEstudiosId
   * @return Doctrine\ORM\QueryBuilder
   */
  public function obtenerPorPlanEstudiosQuery($planEstudiosId) {
    return $this->getRepository()->createQueryBuilder('asignaturaEtapaPlanEstudios')
                    ->join('asignaturaEtapaPlanEstudios.etapaPlanEstudios', 'etapaPlanEstudios')
                    ->join('asignaturaEtapaPlanEstudios.pensumAsignatura', 'pensumAsignatura')
                    ->join('pensumAsignatura.asignatura', 'asignatura')
                    ->add('where','etapaPlanEstudios.planEstudios = :planEstudiosId')
                    ->orderBy('asignatura.nombre', 'ASC')
                    ->setParameter('planEstudiosId', $planEstudiosId);
  }

  /**
   * Crea una nueva entidad dada los id de Etapa y PensumAsignatura
   * @param type $etapaPlanId
   * @param type $pensumAsignaturaId
   */
  public function crearPorIds($etapaPlanId, $pensumAsignaturaId) {
    $em = $this->getEntityManager();
    $entity = new AsignaturaEtapaPlanEstudios();
    $entity->setEtapaPlanEstudios($em->getReference('OpenSkoolAdminBundle:EtapaPlanEstudios', $etapaPlanId));
    $entity->setPensumAsignatura($em->getReference('OpenSkoolAdminBundle:PensumAsignatura', $pensumAsignaturaId));
    $em->persist($entity);
    $em->flush();
  }

  /**
   * Elimina la entidad por el id.
   * @param type $asignaturaEtapaId
   */
  public function eliminarPorId($asignaturaEtapaId) {
    $entity = $this->find($asignaturaEtapaId);
    $em = $this->getEntityManager();
    if ($entity) {
      $em->remove($entity);
      $em->flush();
    }
  }

}
