<?php

namespace OpenSkool\AdminBundle\Entity\Repository;

use Yepsua\RADBundle\ORM\EntityRepository;

use OpenSkool\AdminBundle\Entity\GrupoEtapaPlanEstudios;

/**
 * GrupoEtapaPlanEstudiosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrupoEtapaPlanEstudiosRepository extends EntityRepository
{
  
  
  /**
   * 
   * @param type $etapasIds
   * @return mixed
   */
  public function desagruparEtapas($etapasIds){
    return $this->desagruparEtapasQuery($etapasIds)->execute();
  }
  
  
  /**
   * 
   * @param type $etapasIds
   * @return \Doctrine\ORM\AbstractQuery This query instance.
   */
  public function desagruparEtapasQuery($etapasIds){
    $etapasIds = is_array($etapasIds) ? $etapasIds : explode(",", $etapasIds);
    return $this->getEntityManager()
            ->createQuery('DELETE FROM OpenSkoolAdminBundle:GrupoEtapaPlanEstudios etapa WHERE etapa.id in (:etapasIds)')
            ->setParameter(':etapasIds', $etapasIds);
  }
  
  /**
   * 
   * @param type $etapasIds
   * @return mixed
   */
  public function agruparEtapas($grupoId,$etapasIds){
    $etapasIds = is_array($etapasIds) ? $etapasIds : explode(",", $etapasIds);
    if(sizeof($etapasIds) > 0){
      $em = $this->getEntityManager();
      $grupo = $em->getReference("OpenSkoolAdminBundle:Grupo", $grupoId);
      if($grupo){
        foreach ($etapasIds as $etapaId) {
          $etapa = $this->getEntityManager()->getReference("OpenSkoolAdminBundle:EtapaPlanEstudios", $etapaId);
          $grupoEtapa = new GrupoEtapaPlanEstudios();
          $grupoEtapa->setGrupo($grupo);
          $grupoEtapa->setEtapaPlanEstudios($etapa);
          $em->persist($grupoEtapa);
        }
        $em->flush();
      }
    }
  }
}
