<?php

namespace OpenSkool\AdminBundle\Entity\Repository;

use Yepsua\RADBundle\ORM\EntityRepository;

/**
 * PlanEstudiosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanEstudiosRepository extends EntityRepository
{
}
