<?php

namespace OpenSkool\AdminBundle\Entity\Repository;

use Yepsua\RADBundle\ORM\EntityRepository;

use OpenSkool\AdminBundle\Entity\Prelacion;

/**
 * PrelacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrelacionRepository extends EntityRepository {

  const REPOSITORY_NAMESPACE = 'OpenSkoolAdminBundle:Prelacion';
  
  /**
   * 
   * @param integer $asignaturaId
   * @return array
   */
  public function obtenerPrelacionesAsignatura($asignaturaId = null) {
    $query = $this->obtenerPrelacionesAsignaturaQuery($asignaturaId);
    return $query->getQuery()->getResult();
  }

  /**
   * 
   * @param integer $asignaturaId
   * @return Doctrine\ORM\QueryBuilder
   */
  public function obtenerPrelacionesAsignaturaQuery($asignaturaId) {
    return $this->getRepository()->createQueryBuilder('prelacion')
                    ->add('where','prelacion.asignatura = :asignaturaId')
                    ->setParameter('asignaturaId', $asignaturaId);
  }
  
  /**
   * 
   * @param type $asignaturaId
   * @param type $asignaturaPrelacionId
   * @return type
   */
  public function crearPrelacion($asignaturaId, $asignaturaPrelacionId) {
    $em = $this->getEntityManager();
    $prelacion = new Prelacion();
    $prelacion->setAsignatura($em->getReference(AsignaturaEtapaPlanEstudiosRepository::REPOSITORY_NAMESPACE, $asignaturaId));
    $prelacion->setPrelacion($em->getReference(AsignaturaEtapaPlanEstudiosRepository::REPOSITORY_NAMESPACE, $asignaturaPrelacionId));
    $em->persist($prelacion);
    $em->flush();
  }
  
  /**
   * 
   * @param type $prelacionId
   * @return type
   */
  public function eliminarPorId($prelacionId) {
    $em = $this->getEntityManager();
    $prelacion = $this->find($prelacionId);
    if($prelacion){
      $em->remove($prelacion);
      $em->flush();
    }
  }
  
  /**
   * 
   * @param type $prelacionId
   * @return type
   */
  public function eliminarPrelacion(Prelacion $prelacion) {
    $em = $this->getEntityManager();
    if($prelacion){
      $em->remove($prelacion);
      $em->flush();
    }
  }
}
