<?php

namespace Yepsua\LOVBundle\Entity\Repository;

use Yepsua\RADBundle\ORM\EntityRepository;

/**
 * LOVRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LOVRepository extends EntityRepository
{
  const QUERY_ENTITY_NAME = 'lov';
  
  public function _findAllByGroupName($name)
  {
    return $this->buildQuery()
                ->where('lov_group.groupName = :groupname')
                ->setParameter('groupname', $name)
                ->orderBy('lov.order_by', 'ASC');
  }
  
  protected function getLefJoinsAlias(){
    return array('lov.group' => 'lov_group');
  }
}
