<?php

namespace OpenSkool\PeopleBundle\Entity;

use Yepsua\RADBundle\ORM\EntityRepository;

use OpenSkool\PeopleBundle\Entity\Address;


/**
 * AddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRepository extends EntityRepository
{
    const QUERY_ENTITY_NAME = 'address';
    const ADDRESS_JOIN_NAME = 'address.owners';
    
    protected function getLefJoinsAlias(){
      return array(static::ADDRESS_JOIN_NAME => 'owners');
    }
        
    /**
     * 
     * @param type $ownerId
     * @return type
     */
    public function getAddressesByUserId($ownerId = null){
        $query = $this->buildQuery();
        if($ownerId !== null){
            $query = $query->add('where', 'owners.id = :owner_id');
            $query = $query->setParameter('owner_id', $ownerId);
        }
        return $query;
    }
    
    /**
     * 
     * @param type $ownerId
     * @param \OpenSkool\PeopleBundle\Entity\Address $address
     * @return \OpenSkool\PeopleBundle\Entity\Address
     */
    public function associateAddressesWithUser($ownerId, Address $address){
        $repo = $this->getRepository('OpenSkoolPeopleBundle:Person');
        $owner = $repo->find($ownerId);
        $address->addOwner($owner);
        return $address;
    }    
}
