<?php

namespace Yepsua\LocalityBundle\Entity;

use Yepsua\RADBundle\ORM\EntityRepository;

/**
 * LocalityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocalityRepository extends EntityRepository
{
  const QUERY_ENTITY_NAME = 'locality';
  
  public function _findAllByCountry($countryId)
  {
    $query = null;
    
    if($countryId !== null){
      $query = $this->buildQuery()
                     ->where('locality.country = :id')
                     ->setParameter('id', $countryId)
                     ->orderBy('locality.name', 'ASC');
    }

    return $query;
  }
  
}
