<?php

namespace OpenSkool\AdminBundle\Entity;

use Yepsua\RADBundle\ORM\EntityRepository;

/**
 * ImagenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImagenRepository extends EntityRepository
{
    const ENTITY_NAME = 'imagen';
}
