<?php

namespace OpenSkool\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

use OpenSkool\CoreBundle\Persistence\DAO;

/**
 * InstitutoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstitutoRepository extends EntityRepository
{
    public function getCount()
    {
        return DAO::count($this);
    }
    
    public function isDataNoFound()
    {
        $cInstituo = $this->getCount();
        return $cInstituo <= 0;
    }
}
