<?php

namespace OpenSkool\AdminBundle\Entity;

use Yepsua\RADBundle\ORM\EntityRepository;

use OpenSkool\AdminBundle\Entity\Instituto;

/**
 * PensumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PensumRepository extends EntityRepository
{
    public function synchronizeCarreraWithInstituto(Carrera $carrera){
        $institutos = $this->findAll();
        if($institutos !== null){
            $em = $this->getEntityManager();
            foreach($institutos as $instituto){
                $pensumEstudio = new Pensum();
                $pensumEstudio->setCarrera($carrera);
                $pensumEstudio->setInstituto($instituto);
                $em->persist($pensumEstudio);
            }
            $em->flush();
        }
    }
    
    public function synchronizeInstitutos(Instituto $instituto){
        $carreras = $this->findAll();
        if($carreras !== null){
            $em = $this->getEntityManager();
            foreach($carreras as $carrera){
                $pensumEstudio = new Pensum();
                $pensumEstudio->setCarrera($carrera);
                $pensumEstudio->setInstituto($instituto);
                $em->persist($pensumEstudio);
            }
            $em->flush();
        }
    }
}
