<?php

namespace Yepsua\LocalityBundle\Entity\Repository;

use Yepsua\RADBundle\ORM\EntityRepository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends EntityRepository
{
  const QUERY_ENTITY_NAME = 'city';
  
  public function _findAllByLocality($localityId)
  {
    $query = null;
    
    if($localityId !== null){
      $query = $this->buildQuery()
                     ->where('city.locality = :id')
                     ->setParameter('id', $localityId)
                     ->orderBy('city.name', 'ASC');
    }
    
    return $query;
  }
  
  public function findAllByLocality($localityId)
  {
    return $this->_findAllByLocality($localityId)->getQuery()->getResult();
  }
}
