<?php

namespace Yepsua\LocalityBundle\Entity\Repository;

use Yepsua\RADBundle\ORM\EntityRepository;

/**
 * LocalityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends EntityRepository
{
  const QUERY_ENTITY_NAME = 'country';
  
  public function _findAll()
  {    
    return $this->buildQuery();
  }
}
